# Generated by Django 3.2.8 on 2021-10-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hesap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='İsim')),
                ('total', models.CharField(max_length=50, verbose_name='Tutar')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Ödeme Tarihi')),
                ('shopping_type', models.CharField(max_length=100, verbose_name='Alışveriş Türü')),
            ],
        ),
    ]

