# Generated by Django 3.2.8 on 2021-10-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesap', '0002_alter_hesap_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hesap',
            name='total',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Tutar'),
        ),
    ]
